---
title: "5.3 Least squares regression"
---

420
CHAPTER 5. REGRESSION ANALYSIS
Exercises
5.13
Visualize the residuals. The scatterplots shown below each have a superimposed regression line. If
we were to construct a residual plot (residuals versus x) for each, describe what those plots would look like.
G
G
G
GGGG
GGGG
G
G
GG
G
G
G
G
G
G
G
G
G
GG
G
G
G
G
G
G
G
G
G
GGG
GG
G
G
G
GG
G
GG
GGG
GGG
G
G
G
G
G
GG
G
GG
GGG
G
G
G
GG
GG
G
G
GG
G
GGGG
G
G
G
G
G
G
G
G
G
G
G
G
G
G
G
GG
(a)
G
G
G
G
G
G
G
G
G
G
G
GG
G
G
G
G
GG
G
GG
G
G
G
G
G
G
G
G
G
G
G
G
G
G
G
G
G
G
GG
G
G
GG
G
G
G
G
G
G
G
G
G
G
G
G
G
G
G
G
G
G
G
G
GG
G
G
GGG
GGG
GG
GG
G
GGG
G
G
G
G
GGG
GGGGGGGGG
(b)
5.14
Trends in the residuals.
Shown below are two plots of residuals remaining after fitting a linear
model to two diﬀerent sets of data. Describe important features and determine if a linear model would be
appropriate for these data. Explain your reasoning.
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
GGGG
G
GGGGGGG
GGGGG
G
GG
G
GGGGGGGGG
G
GG
G
GGG
GGGGG
GG
G
G
GG
GG
GG
G
G
G
GG
G
G
G
G
G
GGG
GG
G
GGGG
G
GGG
G
G
G
G
GG
G
G
G
G
GG
G
G
G
GGGG
G
GG
G
G
GGG
GGG
GGGG
G
G
GG
GG
GG
G
G
G
GG
G
GG
G
G
G
G
GGG
G
G
G
G
G
G
G
G
G
GGG
GG
GG
GG
G
G
GG
G
G
G
GG
G
G
G
G
G
G
G
G
G
G
G
G
G
GG
G
G
G
GG
G
GG
G
G
G
G
G
G
G
G
G
G
GG
G
G
G
G
G
G
G
G
G
G
G
G
G
GG
G
G
G
G
GGG
G
G
G
GG
GG
G
G
G
G
G
G
GG
G
G
G
G
G
G
G
G
G
G
G
G
G
GG
G
G
G
G
G
G
G
G
G
G
G
G
G
G
G
G
G
(a)
G
G
GG
G
G
G
G
G
G
GGG
G
G
G
G
G
G
G
GG
G
GGG
G
G
GG
G
GG
GG
G
G
GG
G
GGG
G
GG
G
GGGG
G
G
GGG
G
GG
G
G
G
G
G
G
GGGGGGGGG
G
G
GGG
G
G
G
G
G
G
GG
G
G
G
GGGG
G
G
G
G
G
G
G
G
G
GG
G
G
G
G
GG
G
G
G
GG
G
GGG
GG
G
G
G
GGGG
G
G
GGG
GG
G
G
G
G
GGG
GG
G
GG
GG
GG
G
G
G
G
G
G
G
GG
G
G
GG
G
G
G
GG
GGG
GG
G
GGGGGG
G
G
G
GG
G
GGGG
G
G
G
G
G
G
G
GG
G
GG
GGGGGGG
G
G
G
GGGG
G
G
G
G
GG
GG
GGG
G
GGG
GG
G
G
GG
GG
GGGGG
GGGG
GG
G
G
G
G
G
G
G
GG
G
G
GGG
G
G
GG
G
G
GG
G
G
G
G
G
G
GGG
G
G
G
GG
G
G
G
G
G
GGGG
G
GG
(b)
5.15
Units of regression. Consider a regression predicting weight (kg) from height (cm) for a sample of
adult males. What are the units of the correlation coeﬃcient, the intercept, and the slope?
5.16
Which is higher? Determine if I or II is higher or if they are equal. Explain your reasoning. For a
regression line, the uncertainty associated with the slope estimate, b, is higher when
I. there is a lot of scatter around the regression line or
II. there is very little scatter around the regression line
5.17
Over-under, Part I. Suppose we fit a regression line to predict the shelf life of an apple based on its
weight. For a particular apple, we predict the shelf life to be 4.6 days. The apple's residual is -0.6 days. Did
we over or under estimate the shelf-life of the apple? Explain your reasoning.
5.18
Over-under, Part II. Suppose we fit a regression line to predict the number of incidents of skin cancer
per 1,000 people from the number of sunny days in a year. For a particular year, we predict the incidence of
skin cancer to be 1.5 per 1,000 people, and the residual for this year is 0.5. Did we over or under estimate
the incidence of skin cancer? Explain your reasoning.


### 5.2. LINE FITTING AND RESIDUALS
421
5.19
Tourism spending. The Association of Turkish Travel Agencies reports the number of foreign tourists
visiting Turkey and tourist spending by year.15 Three plots are provided: scatterplot showing the relationship
between these two variables along with the least squares fit, residuals plot, and histogram of residuals.
Number of Tourists
0m
5m
10m
15m
20m
25m
$0
$5b
$10b
$15b
Spending
Number of Tourists
Residuals
0m
5m
10m
15m
20m
25m
-$1b
$0
$1b
(a) Describe the relationship between number of tourists and spending.
(b) What are the explanatory and response variables?
(c) Why might we want to fit a regression line to these data?
(d) Is a linear model appropriate in this context?
5.20
Nutrition at Starbucks, Part I. The scatterplot below shows the relationship between the number of
calories and amount of carbohydrates (in grams) Starbucks food menu items contain.16 Since Starbucks only
lists the number of calories on the display items, we are interested in predicting the amount of carbs a menu
item has based on its calorie content.
Calories
Carbs (grams)
100
200
300
400
500
20
40
60
80
Calories
Residuals
100
200
300
400
500
-20
0
20
Residuals
-40
-20
0
20
40
0
5
10
15
20
25
(a) Describe the relationship between number of calories and amount of carbohydrates (in grams) that
Starbucks food menu items contain.
(b) In this scenario, what are the explanatory and response variables?
(c) Why might we want to fit a regression line to these data?
(d) Is a linear model appropriate in this context?
15Association of Turkish Travel Agencies, Foreign Visitors Figure & Tourist Spendings By Years.
16Source: Starbucks.com, collected on March 10, 2011,
www.starbucks.com/menu/nutrition.


422
CHAPTER 5. REGRESSION ANALYSIS
5.3
Least squares regression
How well can we predict financial aid based on family income for a particular college? How do we
measure the fit of a model and compare diﬀerent models to each other? In this section, we find,
interpret, and apply the least-squares regression line and we investigate a new measure that aims to
tells us about how well a model "fits" the data.
Learning objectives
1. Calculate the coeﬃcients for the least-squares regression line model using technology or identify
them from computer output.
2. Interpret coeﬃcients for the least-squares regression line model.
3. Calculate the coeﬃcient of determination using technology or identify it from from computer
output.
4. Interpret the coeﬃcient of determination.
5.3.1
An objective measure for finding the best line
Fitting linear models by eye is open to criticism since it is based on an individual preference.
In this section, we use least squares regression as a more rigorous approach.
This section considers family income and gift aid data from a random sample of fifty students
in the freshman class of Elmhurst College in Illinois. Gift aid is financial aid that does not need to
be paid back, as opposed to a loan. A scatterplot of the data is shown in Figure 5.18 along with two
linear fits. The lines follow a negative trend in the data; students who have higher family incomes
tended to have lower gift aid from the university.
Family Income ($1000s)
0
50
100
150
200
250
0
10
20
30
Gift Aid From University ($1000s)
Figure 5.18: Gift aid and family income for a random sample of 50 freshman
students from Elmhurst College. Two lines are fit to the data, the solid line being
the least squares line.


### 5.3. LEAST SQUARES REGRESSION
423
We begin by thinking about what we mean by "best". Mathematically, we want a line that has
small residuals. Perhaps our criterion could minimize the sum of the residual magnitudes:
∣y1 -ˆy1∣+ ∣y2 -ˆy2∣+ ⋅⋅⋅+ ∣yn -ˆyn∣
We could fit a line using this criteria with a computer program. The resulting dashed line shown in
Figure 5.18 demonstrates this fit can be quite reasonable. However, a more common practice is to
choose the line that minimizes the sum of the squared residuals:
(y1 -ˆy1)2 + (y2 -ˆy2)2 + ⋅⋅⋅+ (yn -ˆyn)2
The line that minimizes the sum of the squared residuals is represented as the solid line in Figure 5.18.
This is commonly called the least squares line.
Both lines seem reasonable, so why do data scientists prefer the least squares regression line?
One reason is that it is easier to compute by hand and in most statistical software. A more compelling
reason is that in many applications, a residual twice as large as another residual is more than twice
as bad. For example, being oﬀby 4 is usually more than twice as bad as being oﬀby 2. Squaring
the residuals accounts for this discrepancy.
In Figure 5.19, we imagine the squared error about a line as actual squares. The least squares
regression line minimizes the sum of the areas of these squared errors. In the figure, the sum of the
squared error is 4 + 1 + 1 = 6. There is no other line about which the sum of the squared error will
be smaller.
Figure 5.19: A screenshot from the interactive Desmos Activity: Least Squares
Demo. Find it at openintro.org/ahss/desmos. The line is the least squares regression
line as it makes the sum of squared error (in the y direction) least. Here the smallest
possible sum of squared error is 6.


424
CHAPTER 5. REGRESSION ANALYSIS
5.3.2
Writing the least squares regression line
For the Elmhurst College data, we could fit a least squares regression line for predicting gift
aid based on a student's family income and write the equation as:
̂
aid = a + b × family income
Here a is the y-intercept of the least squares regression line and b is the slope of the least squares
regression line. a and b are both statistics that can be calculated from the data.
We can enter all of the data into a statistical software package and easily find the values of a
and b. However, we can also calculate these values by hand, using only the summary statistics.
• The slope of the least squares line is given by
b = r sy
sx
where r is the correlation coeﬃcient between the variables x and y, and sx and sy are the
sample standard deviations of x, the explanatory variable, and y, the response variable.
• The point of averages (¯x, ¯y) is always on the least squares line. Plugging this point in for x
and y in the least squares equation and solving for a gives
¯y = a + b¯x
a = ¯y -b¯x
We mentioned earlier that a computer is usually used to compute the least squares line. A
summary table based on computer output is shown in Figure 5.20 for the Elmhurst College data.
The first column of numbers provides estimates for a and b, respectively.
Estimate
Std. Error
t value
Pr(>∣t∣)
(Intercept)
24.3193
1.2915
18.83
0.0000
family income
-0.0431
0.0108
-3.98
0.0002
Figure 5.20: Summary of least squares fit for the Elmhurst College data.
EXAMPLE 5.16
Using the second, third, and fourth columns in Figure 5.20 is beyond the scope of this book. However,
can you guess what they represent?
Look at the second row, which corresponds to the slope. The first column, Estimate = -0.0431, tells
us our best estimate for the slope of the population regression line. We call this point estimate b.
The second column, Std. Error = 0.0108, is the standard error of this point estimate. The third
column, t value = -3.98, is the T test statistic for the null hypothesis that the slope of the population
regression line = 0. The last column, Pr(>∣t∣) = 0.0002, is the p-value for this two-sided T-test.
EXAMPLE 5.17
Suppose a high school senior is considering Elmhurst College. Can she simply use the linear equation
that we have found to calculate her financial aid from the university?
No. Using the equation will provide a prediction or estimate. However, as we see in the scatterplot,
there is a lot of variability around the line. While the linear equation is good at capturing the trend
in the data, there will be significant error in predicting an individual student's aid. Additionally,
the data all come from one freshman class, and the way aid is determined by the university may
change from year to year.


### 5.3. LEAST SQUARES REGRESSION
425
5.3.3
Interpreting the coefficients of a regression line
Interpreting the coeﬃcients in a regression model is often one of the most important steps in
the analysis.
EXAMPLE 5.18
The slope for the Elmhurst College data for predicting gift aid based on family income was calculated
as -0.0431. Intepret this quantity in the context of the problem.
You might recall from an algebra course that slope is change in y over change in x. The slope of
the regression line tells us about the average change in y for each unit change in x. Here, both x
and y are in thousands of dollars and the slope is negative. So if x is one unit or one thousand
dollars higher, the predicted value of y will be 0.0431 thousand dollars less. In other words, for each
additional thousand dollars of family income, the predicted gift aid is 0.0431 thousand, or $43.10
less.
EXAMPLE 5.19
The y-intercept for the Elmhurst College data for predicting gift aid based on family income was
calculated as 24.3. Intepret this quantity in the context of the problem.
The intercept a describes the predicted value of y when x = 0.
The predicted gift aid is 24.3
thousand dollars if a student's family has no income. The meaning of the intercept is relevant to
this application since the family income for some students at Elmhurst is $0. In other applications,
the intercept may have little or no practical value if there are no observations where x is near zero
(extrapolation). Here, it would be acceptable to say that the average gift aid is 24.3 thousand dollars
among students whose family have 0 dollars in income.
INTERPRETING COEFFICIENTS IN A LINEAR MODEL
• The slope, b, describes the predicted increase or decreases in the response variable y for a
one unit increase of the explanatory variable x.
• The y-intercept, a, describes the predicted outcome of y if x = 0. The linear model must
be valid all the way to x = 0 for this to make sense, which in many applications is not the
case.
GUIDED PRACTICE 5.20
In the previous chapter, we encountered a data set that compared the price of new textbooks for
UCLA courses at the UCLA Bookstore and on Amazon. We fit a linear model for predicting price
at UCLA Bookstore from price on Amazon and we get:
ˆy = 1.86 + 1.03x
where x is the price on Amazon and y is the price at the UCLA bookstore. Interpret the coeﬃcients
in this model and discuss whether the interpretations make sense in this context.17
17The y-intercept is 1.86 and the units of y are in dollars. This tells us that when a textbook costs 0 dollars on
Amazon, the predicted price of the textbook at the UCLA Bookstore is 1.86 dollars. This does not make sense as
Amazon does not sell any $0 textbooks. The slope is 1.03, with units (dollars)/(dollars). For each increase in 1 dollar
that a book costs on Amazon, the predicted cost at the UCLA Bookstore increases by 1.03 dollars. This interpretation
does make sense in this context.


426
CHAPTER 5. REGRESSION ANALYSIS
GUIDED PRACTICE 5.21
Can we conclude that if Amazon raises the price of a textbook by 1 dollar, the UCLA Bookstore
will raise the price of the textbook by $1.03?18
EXERCISE CAUTION WHEN INTERPRETING COEFFICIENTS OF A LINEAR MODEL
• The slope tells us only the average or predicted change in y for each unit change in x;
it does not tell us how much y might change based on a change in x for any particular
individual. Moreover, in most cases, the slope cannot be interpreted in a causal way.
• When a value of x = 0 doesn't make sense in an application, then the interpretation of the
y-intercept won't have any practical meaning. In general, beware of extrapolation.
EXAMPLE 5.22
Use the model ̂
aid = 24.3 -0.0431 × family income to estimate the aid of another freshman student
whose family had income of $1 million.
Recall that the units of family income are in $1000s, so we want to calculate the aid for
family income = 1000:
̂
aid = 24.3 -0.0431 × family income
̂
aid = 24.3 -0.431(1000) = -18.8
The model predicts this student will have -$18,800 in aid (!). Elmhurst College cannot (or at least
does not) require any students to pay extra on top of tuition to attend.
Using a model to predict y-values for x-values outside the domain of the original data is called
extrapolation. Generally, a linear model is only an approximation of the real relationship between
two variables.
If we extrapolate, we are making an unreliable bet that the approximate linear
relationship will be valid in places where it has not been analyzed.
18No. The slope describes the average or overall trend. This is observational data; a causal conclusion cannot be
drawn. Remember, a causal relationship can only be concluded by a well-designed randomized, controlled experiment.
Additionally, there may be large variation in the points about the line. The slope does not tell us how much y might
change based on a change in x for a particular textbook.


### 5.3. LEAST SQUARES REGRESSION
427
5.3.4
Using R2
R2
R2 to describe the strength of a fit
Consider the scatterplot of gift aid versus family income for the Elmhurst College data, graphed
in Figure 5.21. How well does the solid regression line fit the data? And how much better is it than
the horizontal dashed line at ¯y at fitting the data?
Family Income ($1000s)
0
50
100
150
200
250
0
10
20
30
Gift Aid From University ($1000s)
Figure 5.21: Gift aid and family income for a random sample of 50 freshman
students from Elmhurst College, shown with the least squares regression line (ˆy)
and the average line (¯y).
It is common to explain the fit of a model using R2 (R-squared), the coeﬃcient of determi-
nation, also called the explained variance. In Figure 5.21, the variance of the response variable,
aid received, is s2
aid = 29.8. However, if we apply our least squares line, then this model reduces
our uncertainty in predicting aid using a student's family income. The variability in the residuals
describes how much variation remains after using the model: s2
RES = 22.4. We could say that the
reduction in the variance was:
s2
aid -s2
RES
s2
aid
= 29.8 -22.4
29.8
= 7.5
29.8 = 0.25
If we used the simple standard deviation of the residuals (dividing by n -1 instead of n -2), this
would be exactly R2. For large data sets, this gives values suﬃciently close; however, to get the
exact value of R2 we use a sum of squares method, which is described here in general terms.
Recall that we calculate a residual (y -ˆy) to see how well a regression line predicts a particular
y-value. To measure how well the regression line fits all the data, we need to calculate all of the
residuals. We saw in the previous section that the sum of squared residuals is a way of measuring
overall error about a line. In fact, the sum of squared errors about the regression line is smaller
than about any other line. How much smaller is this sum than the sum of squared error about the
line ¯y? Note that we if we do not know x, our best prediction of y is simply ¯y. In a sense, we are
asking how much information using x and the regression line provides over ignoring x all together.
Let us take two extreme examples. In Figure 5.22(a), the correlation coeﬃcient is 0 and the
regression line is the same as the horizontal line at ¯y; the sum of the squared error about ˆy is equal
to the sum of the squared error about ¯y. R2 = 0: the regression line oﬀers no reduction in error; it
"explains" 0% of the variation in the y points.
In Figure 5.22(b), the correlation coeﬃcient is -1 and the regression line goes through all of
the points. There sum of the squared error about the regression line is 0. R2 = 1: the regression line
provides 100% reduction in error and so it "explains" 100% of the variation in the y points.
The exact calculation of R2 is tedious and is done using technology.19
19For those interested, the calculations of R2 in Figure 5.22 can be found as follows. (a) The sum of the squared
error about ˆy and ¯y both equal (-1)2 + (2)2 + (-1)2 = 6. R2 = 6-6
6
= 1 -6
6 = 0. (b) R2 = 8-0
8
= 1 -0
8 = 1.


428
CHAPTER 5. REGRESSION ANALYSIS
(a)
(b)
Figure 5.22: Screenshots from the interactive Desmos Activity: Understanding R2.
Find it at openintro.org/ahss/desmos. (a) R2 = 0. The regression line is equivalent
to ¯y and it explains 0% of the variation in the y points. (b) R2 = 1. The regression
line passes through all of the points and it explains 100% of the variation in the y
points.
R2
R2
R2 IS THE EXPLAINED VARIANCE
R2 is always between 0 and 1, inclusive. R2 tells us the proportion of variation in the response
variable that is explained by a regression model with one or more explanatory variables. The
higher the value of R2, the better the model "explains" the response variable.
EXAMPLE 5.23
The linear model for predicting gift aid from family income for the Elmhurst College data is given
by: ̂
aid = 24.3 -0.0431 × family income. R2 ≈0.25. Interpret this quantity in context.
We can say that about 25% of the variation in gift aid is explained by the linear model with the
explanatory variable x = family income.
The value of R2 is, in fact, equal to r2, where r is the correlation coeﬃcient. This means that
r = +
√
R2 or -
√
R2, depending on direction of the association. Use this fact to answer the next two
practice problems.
GUIDED PRACTICE 5.24
If a linear model has a very strong negative relationship with a correlation coeﬃcient of -0.97, how
much of the variation in the response variable is explained by the linear model?20
GUIDED PRACTICE 5.25
If a linear model has an R2 or explained variance of 0.94, what is the correlation coeﬃcient?21
If R2 is simply the square of the correlation coeﬃcient, why do statisticians prefer using R2 to
assess the fit of a model? The correlation coeﬃcient r only measures linear association, so it only
has meaning for a linear model. R2, on the other hand, measures the fit of any model, whether
linear, quadratic, exponential, etc. Because of this, R2 is more useful for measuring and comparing
the fit of diﬀerent models.
20R2 = (-0.97)2 = 0.94 or 94%. 94% of the variation in y is explained by the linear model.
21We take the square root of R2 and get 0.97, but we must be careful, because r could be 0.97 or -0.97. Without
knowing the slope or seeing the scatterplot, we have no way of knowing if r is positive or negative.


### 5.3. LEAST SQUARES REGRESSION
429
5.3.5
Technology: Scatterplots and regression analysis
The data set loan50, introduced in Chapter 1, contains information on randomly sampled loans.
Download the loan50 CSV file from openintro.org/data. Open it and perform linear regression
analysis for predicting total credit utilized from total credit limit.
Desmos:
1. ENTER DATA: Open the CSV file.
Copy the two columns that correspond to x and y
(the x variable should be on the left). Here we copy the columns total credit limit and
total credit utilized. In a Desmos cell, paste what you copied. You will see the data
presented in a table.
* For small data sets, click + in the upper left, choose table and enter x and y values.
2. SCATTER PLOT and REGRESSION OUTPUT: Click the Add Regression icon shown above.
This will return the least squares regression line in the y = mx + b format, R2, and r as shown
below. Click the magnifying glass in the lower left to Zoom Fit the graphing window. Click the
wrench icon in the upper right to specify the min, max, and step for the X-Axis and Y-Axis
and to add labels to the axes.
3. RESIDUALS and RESIDUAL PLOT: Click plot below the word RESIDUALS. This will add
the residuals to the table and plot them against the x-variable. To make a residual plot, click
the circle next to y in the table to deselect it and click the circle next to "Linear Regression"
to deselect it. Then click the magnifying glass to recenter. Adjust the Y-axis label to be
"residuals".


430
CHAPTER 5. REGRESSION ANALYSIS
4. SUMMARIZE RESIDUALS: Summarize the residuals, here e1, as we did in Chapter 1.
5. NONLINEAR REGRESSION: Make sure the circle next to Linear Regression is selected.
Click on Linear Regression to choose other models. Note that the residuals will update in the
table and on the graph based on the model you select.
6. MANUALLY CREATE regression model: To see the linear regression model in the form
y = a + bx, you can type y1 ∼a + bx1. The ∼is in the upper left of keyboard. Adjust the
number after y and x to match the subscript on your data table. You can also use this method
to manually generate models of your choosing.


### 5.3. LEAST SQUARES REGRESSION
431
R: Scatterplots and Linear Regression Analysis
First read in the x and y values as described on page 52. For simplicity, we use scan(). However,
if you have loaded the openintro package as described near the bottom of page 53 you can use the
dataset$variable structure, e.g. loan50$total credit utilized.
> x = scan()
1:
95131
2:
51929
...
50:
390156
51:
Read 50 items
> y = scan()
1:
32894
2:
78341
...
50:
52534
51:
Read 50 items
Use the lm() function to build a linear model and summary() to summarize it.
> model = lm(y ∼x)
> summary(model)
Residuals:
Min
1Q
Median
3Q
Max
-64713
-28247
-16934
10568
305912
Coefficients:
.
Estimate
Std.Error
t value
Pr(>|t|)
(Intercept) 42410.57946
14210.43201
2.984
0.00446 **
.
x
0.09176
0.05333
1.720
0.09179
---
Residual standard error:
62540 on 48 degrees of freedom
Multiple
R-squared:
0.05808 , Adjusted R-squared:
0.03846
Use plot(x, y) to make a scatterplot. For fun, type help(plot) at the > prompt and investigate
the optional type argument.
> plot(x, y)
> plot(x, y, ylim=c(0,400000), col = "purple", xlab = "Loan Amount ($)",
ylab = "Total Credit Utilized", abline(model, col="red"))
Make a histogram of the residuals and a residual plot, plotting the residuals versus x.
Add xlab = " " and ylab = " " as desired.
> hist(model$residuals)
> plot(x, model$residuals, abline(h=0))


432
CHAPTER 5. REGRESSION ANALYSIS
Calculator: Your teacher may give you data files to work with. Alternately, manually enter data
into a list as described here. NumWorks calculator instructions are included along with example
output. For the TI-83/84 and Casio calculators, general instructions are provided and worked ex-
ample videos can be accessed via the
icon or at openintro.org/ti and openintro.org/casio.
NUMWORKS: REGRESSION
Use OK or EXE to make a selection.
1. Click the yellow Home button (above the black Power button) to get to the home screen.
2. Select Regression and enter the x and y values.
3. Use the up and right arrow and select Graph. This will show you the scatterplot. Use the
left and right arrow to toggle among the data points.
4. Press the up arrow and the right arrow to select Regression. Here you can choose Linear
a+bx format or choose a nonlinear regression. This will draw the regression onto the
scatterplot.
5. Press the up arrow and the right arrow to select Regression again. Here you will see the
regression output. Press the down arrow to see more options, including Residual plot.
6. On the residual plot, use the left and right arrows to select individual points and see their
corresponding residual.
7. Use the arrows to choose Stats at the top to see the summary statistics for x and y. Press
the right arrow to see the y summary statistics. Press down arrow to see more summary
statistics.


### 5.3. LEAST SQUARES REGRESSION
433
TI-84: FINDING a, b, R2
R2
R2, AND r FOR A LINEAR MODEL
Use STAT, CALC, LinReg(a + bx).
1. Choose STAT.
2. Right arrow to CALC.
3. Down arrow and choose 8:LinReg(a+bx).
• Caution: choosing 4:LinReg(ax+b) will reverse a and b.
4. Let Xlist be L1 and Ylist be L2 (don't forget to enter the x and y values in L1 and L2
before doing this calculation).
5. Leave FreqList blank.
6. Leave Store RegEQ blank.
7. Choose Calculate and hit ENTER, which returns:
a
a, the y-intercept of the best fit line
b
b, the slope of the best fit line
r2
R2, the explained variance
r
r, the correlation coeﬃcient
TI-83: Do steps 1-3, then enter the x list and y list separated by a comma, e.g. LinReg(a+bx)
L1, L2, then hit ENTER.
WHAT TO DO IF R2
R2
R2 AND r DO NOT SHOW UP ON A TI-83/84
If r2 and r do now show up when doing STAT, CALC, LinReg, the diagnostics must be turned
on. This only needs to be once and the diagnostics will remain on.
1. Hit 2ND 0 (i.e. CATALOG).
2. Scroll down until the arrow points at DiagnosticOn.
3. Hit ENTER and ENTER again. The screen should now say:
DiagnosticOn
Done
WHAT TO DO IF A TI-83/84 RETURNS: ERR: DIM MISMATCH
This error means that the lists, generally L1 and L2, do not have the same length.
1. Choose 1:Quit.
2. Choose STAT, Edit and make sure that the lists have the same number of entries.


434
CHAPTER 5. REGRESSION ANALYSIS
CASIO FX-9750GII: FINDING a, b, R2
R2
R2, AND r FOR A LINEAR MODEL
1. Navigate to STAT (MENU button, then hit the 2 button or select STAT).
2. Enter the x and y data into 2 separate lists, e.g. x values in List 1 and y values in List
2. Observation ordering should be the same in the two lists. For example, if (5,4) is the
second observation, then the second value in the x list should be 5 and the second value
in the y list should be 4.
3. Navigate to CALC (F2) and then SET (F6) to set the regression context.
• To change the 2Var XList, navigate to it, select List (F1), and enter the proper list
number. Similarly, set 2Var YList to the proper list.
4. Hit EXIT.
5. Select REG (F3), X (F1), and a+bx (F2), which returns:
a
a, the y-intercept of the best fit line
b
b, the slope of the best fit line
r
r, the correlation coeﬃcient
r2
R2, the explained variance
MSe
Mean squared error, which you can ignore
If you select ax+b (F1), the a and b meanings will be reversed.


### 5.3. LEAST SQUARES REGRESSION
435
5.3.6
Types of outliers in linear regression (special topic)
Outliers in regression are observations that fall far from the "cloud" of points. These points
are especially important because they can have a strong influence on the least squares line.
EXAMPLE 5.26
There are six plots shown in Figure 5.23 along with the least squares line and residual plots. For
each scatterplot and residual plot pair, identify any obvious outliers and note how they influence the
least squares line. Recall that an outlier is any point that doesn't appear to belong with the vast
majority of the other points.
(1) There is one outlier far from the other points, though it only appears to slightly influence the
line.
(2) There is one outlier on the right, though it is quite close to the least squares line, which
suggests it wasn't very influential.
(3) There is one point far away from the cloud, and this outlier appears to pull the least squares
line up on the right; examine how the line around the primary cloud doesn't appear to fit very
well.
(4) There is a primary cloud and then a small secondary cloud of four outliers. The secondary
cloud appears to be influencing the line somewhat strongly, making the least squares line fit
poorly almost everywhere. There might be an interesting explanation for the dual clouds,
which is something that could be investigated.
(5) There is no obvious trend in the main cloud of points and the outlier on the right appears to
largely control the slope of the least squares line.
(6) There is one outlier far from the cloud, however, it falls quite close to the least squares line
and does not appear to be very influential.
Examine the residual plots in Figure 5.23. You will probably find that there is some trend in
the main clouds of (3) and (4). In these cases, the outliers influenced the slope of the least squares
lines. In (5), data with no clear trend were assigned a line with a large trend simply due to one
outlier (!).
LEVERAGE
Points that fall horizontally away from the center of the cloud tend to pull harder on the line,
so we call them points with high leverage.
Points that fall horizontally far from the line are points of high leverage; these points can
strongly influence the slope of the least squares line. If one of these high leverage points does appear
to actually invoke its influence on the slope of the line - as in cases (3), (4), and (5) of Example 5.26
- then we call it an influential point. Usually we can say a point is influential if, had we fitted the
line without it, the influential point would have been unusually far from the least squares line.
It is tempting to remove outliers. Don't do this without a very good reason. Models that ignore
exceptional (and interesting) cases often perform poorly. For instance, if a financial firm ignored the
largest market swings - the "outliers" - they would soon go bankrupt by making poorly thought-out
investments.
DON'T IGNORE OUTLIERS WHEN FITTING A FINAL MODEL
If there are outliers in the data, they should not be removed or ignored without a good reason.
Whatever final model is fit to the data would not be very helpful if it ignores the most exceptional
cases.


