const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');
const { marked } = require('marked');

// Directory paths
const CONTENT_DIR = path.join(__dirname, '..', 'content');
const OUTPUT_FILE = path.join(__dirname, '..', 'js', 'generated_content.js');

// Custom regex to handle Quarto Callouts (::: {.callout-type title="Title"})
function parseQuartoCallouts(markdown) {
  // Regex to match ::: {.callout-xxx title="yyy"} ... :::
  // We handle it by replacing it with custom HTML tags that our CSS will style
  let processed = markdown;
  
  // Replace starting tag ::: {.callout-xxx title="yyy" collapse="zzz"}
  const startRegex = /:::\s*\{\s*\.callout-([a-zA-Z0-9_-]+)(?:[^}]*title="([^"]+)")?[^}]*\}/g;
  processed = processed.replace(startRegex, (match, type, title) => {
    let cssClass = 'concept-box'; // default
    if (type === 'tip') cssClass = 'ti84-box';
    if (type === 'warning') cssClass = 'warning-box';
    if (type === 'note') cssClass = 'concept-box';
    
    let html = `<div class="${cssClass}">`;
    if (title) {
      html += `<h4 class="callout-title">${title}</h4>`;
    }
    html += `<div class="callout-body">`;
    return html;
  });

  // Replace ending tag :::
  // Note: this simple regex assumes no nested :::
  // A better way is to replace lines exactly equal to :::
  processed = processed.replace(/^:::\s*$/gm, '</div></div>');

  return processed;
}

function processDirectory(dirPath) {
  const result = {};
  if (!fs.existsSync(dirPath)) return result;

  const files = fs.readdirSync(dirPath);
  for (const file of files) {
    const fullPath = path.join(dirPath, file);
    const stat = fs.statSync(fullPath);

    if (stat.isDirectory()) {
      result[file] = processDirectory(fullPath);
    } else if (file.endsWith('.qmd') || file.endsWith('.md')) {
      const content = fs.readFileSync(fullPath, 'utf8');
      const parsed = matter(content);
      
      let markdownContent = parsed.content;
      markdownContent = parseQuartoCallouts(markdownContent);
      
      // Fix image paths: Quarto uses ../../assets, we need to point to content/assets/
      markdownContent = markdownContent.replace(/(\.\.\/)*assets\//g, 'content/assets/');

      const htmlContent = marked.parse(markdownContent);
      
      const basename = path.basename(file, path.extname(file));
      result[basename] = {
        metadata: parsed.data,
        html: htmlContent
      };
    }
  }
  return result;
}

function build() {
  console.log('Starting content build process...');
  
  const courseData = {
    units: processDirectory(path.join(CONTENT_DIR, 'units')),
    practice: processDirectory(path.join(CONTENT_DIR, 'practice')),
    assessment: processDirectory(path.join(CONTENT_DIR, 'assessment')),
    labs: processDirectory(path.join(CONTENT_DIR, 'labs'))
  };

  const outputJs = `// THIS FILE IS AUTO-GENERATED BY scripts/build_content.js\n\nconst GENERATED_COURSE_DATA = ${JSON.stringify(courseData, null, 2)};\n`;
  
  fs.writeFileSync(OUTPUT_FILE, outputJs, 'utf8');
  console.log(`Successfully generated content to ${OUTPUT_FILE}`);
}

build();
